"""Remove content field from Message table

Revision ID: 3bada0c36c76
Revises: 9dc74b5b2a08
Create Date: 2026-02-21 12:01:03.516557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bada0c36c76'
down_revision: Union[str, Sequence[str], None] = '9dc74b5b2a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
