"""Add fingerprint to Users table

Revision ID: 559236330a9c
Revises: 7e4b8dc66cb4
Create Date: 2026-02-20 18:23:53.692583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559236330a9c'
down_revision: Union[str, Sequence[str], None] = '7e4b8dc66cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fingerprint', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_fingerprint'), 'users', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_fingerprint'), table_name='users')
    op.drop_column('users', 'fingerprint')
    # ### end Alembic commands ###
