"""Update Users table

Revision ID: 7e4b8dc66cb4
Revises: 5a84f0bc85d0
Create Date: 2026-02-20 13:38:22.310576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4b8dc66cb4'
down_revision: Union[str, Sequence[str], None] = '5a84f0bc85d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'enc_private_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'enc_private_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'public_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
