name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code and rebuild
        run: |
          cd /home/ubuntu/sentinel-app/sentinel-backend
          git pull origin main          
          cd ..

          docker-compose up -d --build fastapi
          docker-compose exec -T fastapi uv run alembic upgrade head
          
      - name: Cleanup
        run: docker image prune -f