name: Deploy Backend

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code and rebuild
        run: |
          cd /home/ubuntu/sentinel-app/sentinel-backend
          git fetch origin main
          git reset --hard origin/main
          
          docker compose up -d redis postgres
          
          docker compose run --rm fastapi uv run alembic upgrade head
          
          docker compose up -d --build fastapi
          
      - name: Cleanup
        run: docker image prune -f